inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
  TargetRubyVersion: 2.0

# This doesn't understand that <<~ doesn't exist in 2.0
Style/IndentHeredoc:
  Enabled: false

# This doesn't take into account retrying from an exception
Lint/HandleExceptions:
  Enabled: false

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow the use of globals which makes sense in a CLI app like this
Style/GlobalVars:
  Enabled: false
