Sorbet:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true
  Exclude:
    - lib/spin/sorbet_runtime_stub.rb

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "**/*.rb"
    - "**/*.rbi"
    - "**/*.rake"
    - "**/*.ru"
  Exclude:
    - lib/spin/sorbet_runtime_stub.rb
    - "test/**/*"

Sorbet/EnforceSigilOrder:
  Enabled: true

Sorbet/EnforceSignatures:
  Enabled: true
  Exclude:
    - lib/spin/sorbet_runtime_stub.rb
    - "test/**/*"

Sorbet/SignatureBuildOrder:
  Enabled: true

Sorbet/KeywordArgumentOrdering:
  Enabled: true

Sorbet/ConstantsFromStrings:
  Enabled: true

Sorbet/ForbidIncludeConstLiteral:
  Enabled: false
