up:
  - homebrew:
      - fswatch
  - ruby: 3.0.2
  - bundler

commands:
  console: irb -I./lib -rcli/kit
  check:
    run: 'srb && rake style test'
    aliases: [ck]
  test: rake test
  style:
    run: rake style
    aliases: [st]
  typecheck:
    run: srb
    aliases: [tc]
  watch:
    aliases: [w]
    subcommands:
      style:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ rake style
        aliases: [st]
      test:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ rake test
        alises: [t]
      typecheck:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ srb
        aliases: [tc]
      check:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ bash -c 'srb && rake style test'
        aliases: [ck]
